'use client'
import { useEffect } from 'react'
import { Camera, ShieldAlert, Video } from 'lucide-react'
import { useParams } from 'react-router-dom'
import { Card, Header } from '@/components/shared'
import { useMonitorStore } from '@/store/monitorStore'
import { useExamMonitor } from '@/hooks/useExamMonitor'
import type { AnalyticsOverview } from '@/types/ai'
const overview: AnalyticsOverview = { completionRate: 78, averageScore: 82, flaggedAttempts: 7, activeSessions: 24, scoreTrend: [{label:'Mon',value:74},{label:'Tue',value:79},{label:'Wed',value:77},{label:'Thu',value:84},{label:'Fri',value:82}], difficultyTrend: [{label:'Easy',value:31},{label:'Medium',value:49},{label:'Hard',value:20}], riskDistribution: [{label:'Low',value:68},{label:'Medium',value:24},{label:'High',value:8}] }


export function ProctorMonitor() { const { id = 'attempt-1' } = useParams(); useExamMonitor(id); const { webcam, events, setWebcam } = useMonitorStore(); useEffect(() => { setWebcam({ supported: !!navigator.mediaDevices?.getUserMedia }); }, [setWebcam]); return <><Header title="Live proctoring monitor" description="Review session health and risk signals from the active exam."/><div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><Card><div className="flex items-center justify-between"><div><p className="text-sm text-muted-foreground">Session status</p><p className="mt-1 flex items-center gap-2 font-semibold text-emerald-600"><span className="size-2 rounded-full bg-emerald-500"/> Monitoring active</p></div><ShieldAlert className="text-amber-600"/></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-muted p-4"><p className="text-xs text-muted-foreground">Risk score</p><p className="mt-1 text-2xl font-semibold">Low</p></div><div className="rounded-xl bg-muted p-4"><p className="text-xs text-muted-foreground">Events</p><p className="mt-1 text-2xl font-semibold">{events.length}</p></div><div className="rounded-xl bg-muted p-4"><p className="text-xs text-muted-foreground">Connection</p><p className="mt-1 text-2xl font-semibold">Good</p></div></div><div className="mt-6 space-y-3">{events.length ? events.map((event, index) => <div key={`${event.type}-${index}`} className="flex justify-between rounded-xl border border-border p-3 text-sm"><span>{event.type.replaceAll('_', ' ')}</span><span className="text-muted-foreground">{new Date(event.timestamp).toLocaleTimeString()}</span></div>) : <p className="rounded-xl bg-muted p-4 text-sm text-muted-foreground">No proctoring events detected.</p>}</div></Card><Card><div className="flex items-center gap-2"><Video className="text-primary"/><h2 className="font-semibold">Webcam status</h2></div><div className="mt-5 grid place-items-center rounded-2xl bg-slate-950 py-16 text-slate-300"><Camera size={32}/><p className="mt-3 text-sm">Camera preview ready</p></div><p className="mt-4 text-sm text-muted-foreground">{webcam.supported ? 'Browser camera support detected. Connect the backend stream to enable live frames.' : 'Camera support is unavailable in this browser.'}</p></Card></div></> }
export function AdminAnalytics() { return <><Header title="AI analytics" description="Understand performance, adaptive difficulty, and examination risk at a glance."/><div className="grid gap-4 md:grid-cols-4">{[['Completion rate', `${overview.completionRate}%`], ['Average score', `${overview.averageScore}%`], ['Flagged attempts', overview.flaggedAttempts], ['Active sessions', overview.activeSessions]].map(([label, value]) => <Card key={label}><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></Card>)}</div><div className="mt-5 grid gap-5 lg:grid-cols-2"><Card><h2 className="font-semibold">Score trend</h2><div className="mt-6 flex h-40 items-end gap-3">{overview.scoreTrend.map((point) => <div key={point.label} className="flex flex-1 flex-col items-center gap-2"><div className="w-full rounded-t-lg bg-primary" style={{ height: `${point.value}%` }}/><span className="text-xs text-muted-foreground">{point.label}</span></div>)}</div></Card><Card><h2 className="font-semibold">Risk distribution</h2><div className="mt-6 space-y-4">{overview.riskDistribution.map((point) => <div key={point.label}><div className="mb-1 flex justify-between text-sm"><span>{point.label}</span><span>{point.value}%</span></div><div className="h-2 rounded-full bg-muted"><div className="h-2 rounded-full bg-primary" style={{ width: `${point.value}%` }}/></div></div>)}</div></Card></div></> }
