spring.application.name=examora-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/examora_db
spring.datasource.username=examora_user
spring.datasource.password=examora_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=examora-super-secret-key-change-this-later-123456789
app.jwt.expiration=86400000
logging.level.org.springframework.security=DEBUG
